name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    - name: Configure Git identity
      run: |
        git config --global user.name "Andrchest"
        git config --global user.email "andreipolevoi220@gmail.com"
    - name: Push to Hugging Face Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git checkout -b hf-single-commit
        git reset --soft $(git rev-list --max-parents=0 HEAD)
        git commit -m "Single commit for Hugging Face"
        echo "samples/sample.pdf" >> .gitignore
        git add .gitignore
        git commit -m "Update .gitignore to ignore samples/sample.pdf"
        git remote add hf https://Andrchest:$HF_TOKEN@huggingface.co/spaces/Andrchest/The-Ultimate-RAG
        git push --force hf hf-single-commit:main