name: Unit Tests
on:
  pull_request:
    branches:
      - main
permissions:
  issues: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Run unit tests
        run: |
          python -m unittest app/tests/unit/test.py
      - name: Notify on success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const message = 'Unit tests succeeded!';
            if (context.payload.pull_request) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: message
              });
            } else {
              console.log(message);
            }
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const message = 'Unit tests failed. Check GitHub Actions logs for details.';
            if (context.payload.pull_request) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: message
              });
            } else {
              console.log(message);
            }